version: '3'
services:
  nginx:
      image: nginx:1.21.5-alpine
      ports:
        - 80:80
      volumes:
        - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      container_name: myweb-proxy
      depends_on:
        - frontend
        # - backend
  frontend:
    image: 'lkw9/ndp-fe:${DOCKER_TAG}'
    container_name: front
    restart: always
    ports:
      - "3000:3000"

  # backend:
  #   image: minjik0525/ndp-back:latest
  #   container_name: back
  #   restart: always
  #   ports:
  #     - "8080:8080"

  # networks:
  #   default:
  #     driver: bridge
