# version: "3.7"
# services:
#     # nginx:
#     #     build:
#     #         context: ./nginx
#     #         dockerfile: Dockerfile
#     #     ports:
#     #         - "80:80"
#     #     container_name: cst-nginx
#     #     depends_on:
#     #         - web
#     #         - api