name: FE Docker Hub Image

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: DockerFile
        push: true
        tags: lkw9/ndp-fe:${{secrets.DOCKER_TAG}}
        
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
            # sudo docker-compose -f $COMPOSE down
            sudo docker pull lkw9/ndp-fe:${{secrets.DOCKER_TAG}}
            # sudo docker-compose -f $COMPOSE up -d
