name: FE Docker Hub Image

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Environment Variables File for Production
      run: |
         echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
         echo "NEXT_PUBLIC_KAKAO_REDIRECT_URI=$NEXT_PUBLIC_KAKAO_REDIRECT_URI" >> .env
         echo "NEXT_PUBLIC_GOOGLE_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_REDIRECT_URI" >> .env
         echo "NEXT_PUBLIC_NAVER_REDIRECT_URI=$NEXT_PUBLIC_NAVER_REDIRECT_URI" >> .env
         echo "NEXT_PUBLIC_FORBIDDENWORDS=$NEXT_PUBLIC_FORBIDDENWORDS" >> .env
         echo "NEXT_PUBLIC_KAKAO_API_KEY=$NEXT_PUBLIC_KAKAO_API_KEY" >> .env
         echo "DOCKER_TAG=$DOCKER_TAG" >> .env
      env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_KAKAO_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_KAKAO_REDIRECT_URI }}
          NEXT_PUBLIC_GOOGLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}
          NEXT_PUBLIC_NAVER_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_NAVER_REDIRECT_URI }}
          NEXT_PUBLIC_FORBIDDENWORDS: ${{ secrets.NEXT_PUBLIC_FORBIDDENWORDS }}
          NEXT_PUBLIC_KAKAO_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_API_KEY }}
          DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
    
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    # - name: Build and Push Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: DockerFile
    #     push: true
    #     tags: lkw9/ndp-fe:latest
        
    - name: Deploy 1
      uses: appleboy/ssh-action@master
      env:
          APP: "preonb"
          COMPOSE: "/home/ubuntu/compose/docker-compose.yml"
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        envs: APP, COMPOSE
        script_stop: true
        script: |
            sudo apt update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            sudo apt update
            sudo apt install -y docker-ce
            sudo usermod -aG docker ${{ secrets.REMOTE_SSH_ID }}
            sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            mkdir -p /home/${{ secrets.REMOTE_SSH_ID }}/compose
            cd /home/${{ secrets.REMOTE_SSH_ID }}/compose
            echo ${{ secrets.COMPOSE }} | base64 --decode > ./docker-compose.yml  
            echo ${{ secrets.NGINX_CONF}} | base64 --decode > ./nginx.conf 
            sudo docker-compose -f /home/ubuntu/compose/docker-compose.yml down --rmi all
            sudo docker-compose -f /home/ubuntu/compose/docker-compose.yml up -d 


